name: Commit
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/ .npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.jspon') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install NPM dependencies
        run: |
          npm ci --prefer-offline --no-audit
      - name: Linter
        run: |
          npm run lint -- \
            --format junit \
            --output-file test-results/eslint/TEST-eslint.xml
  
  e2e-tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install Playwright Dependencies
        run: npx playwright install-deps
      
      - name: Install NPM Dependencies
        run: npm install
        
      - name: Run Tests In Chrome
        run: npm run test:headless:chrome
      
        - name: Run Tests In Firefox
        run: npm run test:headless:firefox
    
            
  
